search_space:
  batch_size:
  - 32
  epochs:
  - 200
  learning_rate:
  - 0.001
  - 0.0005
  - 0.0001
  lr_scheduler:
  - step
  - cosine
  - none
  model_name:
  - resnet18
  momentum:
  - 0.9
  - 0.8
  - 0.0
  num_classes:
  - 2
  optim:
  - Adam
  - SGD
  pretrained:
  - false
  scheduler_gamma:
  - 0.5
  scheduler_step_size:
  - 5
  scheduler_t_max:
  - 50
trainer_config:
  balancing_strategy: weighted_loss
  class_weights:
    0: 0.4255707762557077
    1: 0.5744292237442922
  device: cuda
  early_stopping: true
  fold_seeds:
  - 42
  - 43
  main_metric: loss
  model_builder: !!python/name:utils.model.get_model ''
  optimizer_builder: !!python/name:utils.optimizer.get_optimizer ''
  patience: 30
  shuffle: false
